hydra:
  run:
    dir: hydra_output/

comet_ml:
  api_key: LSTIie51umcysQtnef1Zzil6V
  project_name: moa-prediction

exp:
  exp_name: test

train:
  g_comp: 29
  c_comp: 4
  var_thresh: 0.5
  batch_size: 128
  hidden_size: 2048
  dropout_rate: 0.4
  epoch: 50
  seed: 42
  fold: 3
  lr: 0.001