hydra:
  run:
    dir: hydra_output/

comet_ml:
  api_key: LSTIie51umcysQtnef1Zzil6V
  project_name: moa-prediction

exp:
  exp_name: test

train:
  batch_size: 128
  hidden_size: 2048
  dropout_rate: 0.4
  epoch: 20
  seed: 42
  fold: 0
  lr: 0.00005